### ISSUE TITLE
Add capabilities and/or protections around logging

### ISSUE THREAD

**Issue by JakeOShannessy** [Daolab/beaker-preprocessor#13]
With the addition of kernel logs, it will likely be assumed that these logs are accurate, therefore we want to restrict Beaker Procedures from arbitrarily writing to logs. This is less about capabilities and more about protections. For example, any procedure that has Storage write access will need to write to these logs, but they should only do so as part of a protected storage call.

Perhaps logging capabilities can come at a later date, but we need to check and restrict arbitrary log writing when processing bytecode.

**Comment by JakeOShannessy** [comment]
As with #8, this is not what we are doing any more and should be closed.

**Comment by Latrasis** [comment]
@JakeOShannessy: I'm guessing you mean that we have already described the capability table, correct?

**Comment by Latrasis** [comment]
Agreed
