### ISSUE TITLE
beaker-cli and `beaker compile`

### ISSUE THREAD

**Issue by Latrasis** [Daolab/beaker-preprocessor#8]
## Context
Right now, since what we have is only a library there is no clear endpoint or friendly process how to create a procedure from a compiled solidity contract `abi` definition. Most developers are not familiar with haskell, and requiring developers to use the library directly would present a barrier to adoption.

## Proposal
Introduce a cli aka `beaker-cli` that provides a clear interface for interaction. To start with, we need to able to parse a `ContractAbi.json`, parse it's opcode, protect Stores, and produce a new `ProtectedContractAbi.json` as a result. 

For the sake of this proposal, let's call this command `compile`. It recieves a input path as input and an output path: `beaker compile <input_abi> <output_abi>`. 

### Adding Capabilities
By default, a procedure should have the minimum amount of capabilities.
To tell beaker to add a capability, we can define a `--cap [capability]` option that parses a list.

Since we only have storage protection we have:
* `read(id: u8)`: Denotes read access to keys starting with id
* `write(id: u8)`: Denotes write access to keys starting with id

## Example
```bash

# Compile a solidity contract Foo
solc Foo.sol FooAbi.json

# Compile-Transform FooAbi.json to FooPureAbi.json
# By default, FooPureAbi will not have a access to any state
beaker compile FooAbi.json FooPureAbi.json

# To add a capability to FooImpureAbi:
beaker compile FooAbi.json FooImpureAbi.json --cap write(0x1) read(0x1)

```

**Comment by JakeOShannessy** [comment]
This exists in some form, but it isn't the direction we are taking any more. We should probably close this.

**Comment by Latrasis** [comment]
Agreed. Since now capabilities will be stored on-chain, this will not be applicable.
